title: "[全編無料] 他言語習得者がとりあえず使えるようになるZig"
summary: "公式ドキュメントを私的に噛み砕きつつ、いくつかのコラムを添えて、Zigに入門する本です。"
topics: ["zig"]
published: false
price: 500
chapters:
- introduction
- using-test-as-samples
- about-zig
- about-zig-robustness
- about-zig-reusability
- primitive-type
- primitive-type-integer
- primitive-type-etc
- using-zig-stdlib-parser
- history
- after-talk

