title: "[全編無料][鋭意執筆中] 他言語習得者がとりあえず使えるようになるZig"
summary: >-
    公式ドキュメントを私的に噛み砕きつつ、いくつかのコラムを添えて、Zigに入門する本です。
    この本を読めばZigの機能を網羅できるわけではありませんが、取っ掛かりがつかめる様になると思います。
    なお、この本は現在も鋭意執筆中ですので、未完成の章があったり、情報が書き加えられる可能性があります。
topics: ["zig"]
published: true 
price: 500
chapters:
- introduction
- using-test-as-samples
- about-zig
- about-zig-robustness
- about-zig-reusability
- type-system-walkthrough
- primitive-type
- primitive-type-integer
- primitive-type-etc
- array
- vector
- pointer
- slice
- optional
- struct
- enum
- union
- error-handling
- block
- switch
- defer
- function
- comptime
- memory-allocator
- stdlib-json
- stdlib-fmt
- stdlib-io
- code-reading-stdlib-arraylist
- using-zig-stdlib-parser
- history
- after-talk

